### ISSUE TITLE
依赖的 pyoauth2 是什么版本的啊？

### ISSUE THREAD

**Issue by node** [douban/douban-client#10]
我下载了 douban-client 的python sdk，测试的时候发现以下错误：

```
from pyoauth2 import Client, AccessToken
ImportError: cannot import name Client
```

然后检查了下 pyoauth2 ，从 http://pypi.python.org/pypi/pyoauth2 这里下载的；说的是0.0.4，其实包里面有个文件信息没改，显示还是 0.0.3 。

但是包里可以导入的 是 client, 而不是 Client， 也不能到 AccessToken 。

建议在指明下依赖包的版本吧，最好包含下载链接 :)

**Comment by liluo** [comment]
依赖 py-oauth2  在 http://pypi.python.org/pypi/py-oauth2/0.0.5

打包的 setup.py 中有指定 install_requires = ['py-oauth2>=0.0.5']，在 pip install douban-client 时应该会自动安装 py-oauth2 这个依赖。

**Comment by lisongx** [comment]
可以加个requirements.txt么?

**Comment by liluo** [comment]
@seansay 已加。

**Comment by node** [comment]
卸载了其他版本的，重新安装，OK；
问题已解决，感谢！
