### ISSUE TITLE
client.user.me 提示错误 403 (Forbidden)

### ISSUE THREAD

**Issue by wangwangwra** [douban/douban-client#14]
测试的 examples 里的 auth_with_password.py 代码。提供了 apikey 和 secret，用户名和密码也提供了。命令行打印
douban_client.api.error.DoubanError: **_403 (Forbidden)**_ {u'msg': u'need_permission', u'code': 1000, u'request': u'GET /v2/user/~me'}

看到 callback 地址和申请的不一样，以为是这里错了，结果改成一样了还是同样的错误。
提示权限不够，但是 scope 里的 douban_basic_common 和 community_basic_user 应该够了撒？
谢谢关注！

**Comment by liluo** [comment]
auth_with_password 需要申请 xauth 权限，具体的申请方法和流程我也不太清楚，请到 http://www.douban.com/group/dbapi/ 咨询。

**Comment by wangwangwra** [comment]
原来如此！谢谢！
