### ISSUE TITLE
pyoauth2好像不支持3.2版本的

### ISSUE THREAD

**Issue by PacoIrene** [douban/douban-client#17]
下载最新的但安装之后执行from douban_client import DoubanClient会报错，然后发现pyoauth2里面很多类似于urlparse和StringIO等都已经不支持3.2的版本

**Comment by liluo** [comment]
py-oauth2 和 douban-client 暂时没有对 Py 3.x 做兼容。

**Comment by tonyseek** [comment]
是否考虑像 Django 那样，用 `six` 来做 2.x 与 3.x 的兼容呢？
