### ISSUE TITLE
木有refresh_token() 吗

### ISSUE THREAD

**Issue by oangeor** [douban/douban-client#18]
RT

**Comment by liluo** [comment]
@oangeor 暂时木有，如果有需求的话可以很快加上，需要嘛？

**Comment by lisongx** [comment]
会很有用;)

**Comment by oangeor** [comment]
@liluo 有这个需要，THX

**Comment by liluo** [comment]
@oangeor done. 

代码提交在 https://github.com/douban/douban-client/commit/a0d684bd9144e6ec1caff0989054adde1e9daf10;

可以使用 `pip install douban-client==0.0.4` 或者 `easy_install -U "douban-client==0.0.4"` 来安装;

使用见 https://github.com/douban/douban-client#oauth-20- `Refresh Token` 部分.

cc @seansay

**Comment by oangeor** [comment]
THX @liluo
