### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'get'

### ISSUE THREAD

**Issue by benqbook** [douban/douban-client#2]
采用client.movie.get(id)方法获取电影信息时，报错：
AttributeError: 'Client' object has no attribute 'get'

查了下
/usr/local/lib/python2.6/dist-packages/py_oauth2-0.0.3-py2.6.egg/oauth2/client.py
中Client类的实现，确实没有get方法

求助！

**Comment by liluo** [comment]
你应该是没有成功完成授权，在成功授权之后， py-oauth2 这里会是 AccessToken 对象。

**Comment by liluo** [comment]
另外，我在 http://doudev.com:5000/ 有一个获取电影条目信息的 demo，测试是 ok 的。

**Comment by benqbook** [comment]
问题解决了，确实是未成功授权所造成的，多谢liluo !
