### ISSUE TITLE
解释器运行from douban_client import DoubanClient报错

### ISSUE THREAD

**Issue by Sayi** [douban/douban-client#24]
您好，我是个python **新手** ，在解释器中运行如题脚本时报错，望答复。谢谢。 
使用环境为python3.2，windows7 cmd 或者 windows GitBash 
1.安装  

```
pip install douban-client
```

安装完成后，在路径Lib\site-packages下，可以看到安装了一下包(版本为包中**init**.py中所示)：  
douban_client     '0.0.5'
httplib2  
pyoauth2   '0.0.6'

2.此时我试着通过解释器运行如下代码：  

```
from douban_client import DoubanClient
```

报如下错误：  

```
File "c:\Python33\lib\site-packages\pyoauth2\__init__.py", line 3, in <module>
from client import Client
ImportError: No module named 'client'  
```

我尝试着解决这个错误，修改Lib\site-packages\pyoauth2、**init**.py，将导入代码  

```
from client import Client
```

修改为  

```
from .client import Client  
```

然后尝试运行脚本，报如下错误  

```
File "c:\Python33\lib\site-packages\pyoauth2\__init__.py", line 3, in <module>
from .client import Client
File "c:\Python33\lib\site-packages\pyoauth2\client.py", line 3, in <module>
from libs.auth_code import AuthCode
ImportError: No module named 'libs.auth_code'
```

不知道这是为什么？好吧，写了这么多，发现 @liluo 的一个issue里面的回答：  

> py-oauth2 和 douban-client 暂时没有对 Py 3.x 做兼容。  

好吧，看来我继续学习了，这个issue关闭了吧。。

**Comment by Sayi** [comment]
谢谢啦。。

**Comment by liluo** [comment]
@Sayi 不好意思，我手头上没有 win 开发环境，等我空一些的时候会做一下 3.x 的兼容工作。
