### ISSUE TITLE
example里的代码运行不了

### ISSUE THREAD

**Issue by NobodyWHU** [douban/douban-client#25]
我尝试过with_password和with_code，每次都是返回403 Forbidden。
我的SCOPE已经 设为shuo_basic_r,shuo_basic_w,douban_basic_common

问题2：我尝试在api的User类下面添加一个自定义方法，在使用的时候会发生找不到此属性，请问我应该怎么做

**Comment by liluo** [comment]
> 我尝试过with_password和with_code，每次都是返回403 Forbidden。
> 我的SCOPE已经 设为shuo_basic_r,shuo_basic_w,douban_basic_common

`with_password` 是需要申请 xauth 的权限；
`with_code` 是指 [examples/auth_with_code.py](https://github.com/douban/douban-client/blob/master/examples/auth_with_code.py) 这个吗？你有写入自己的 API key、secret 吗？方便的话贴个 secret 的 gist 给看一下？

> 问题2：我尝试在api的User类下面添加一个自定义方法，在使用的时候会发生找不到此属性，请问我应该怎么做

是将这个仓库 clone 放入项目中吗？这样应该是 ok 的，可否将使用方式及“自定义”描述的详细一些？

**Comment by NobodyWHU** [comment]
之前写过一个回复，修改的时候不小心删了，好心酸

---

1.在之前的问题中您是回复豆瓣API小组的链接，在之中我搜索xauth并没有得到清除的答案，还得继续了解。
2.是 examples/auth_with_code.py这个文件。写入的key和secret都是审核通过的，secret为3367ec9f518b6b45
回调网址我是随意指定的一个博客，授权后跳转的url中带有一个code参数，我想这应该是我所需要的code值。纠正下，之后的报错为400 Bad Request。
3.我使用的Clone in windows工具下载代码，应该没问题。在豆瓣用户API中，包含这样一个方法获取用户信息 
GET /v2/user/:name
我在user.py中加入以下代码
def get_name(self, name):
        return self._get('/v2/user/:%s' % name)
测试使用是报错 User has not attribute 'get_name'  初学者，可能是一个很愚蠢的问题

---

第二个问题可能先放一放，我发现在申请权限时没包含豆瓣公共

**Comment by liluo** [comment]
> 2.是 examples/auth_with_code.py这个文件。写入的key和secret都是审核通过的，secret为3367ec9f518b6b45
> 回调网址我是随意指定的一个博客，授权后跳转的url中带有一个code参数，我想这应该是我所需要的code值。纠正下，之后的报错为400 Bad Request。

`400 Bad Request` 应该还会返回错误代码及信息，贴一下？

> 3.我使用的Clone in windows工具下载代码，应该没问题。在豆瓣用户API中，包含这样一个方法获取用户信息 
> GET /v2/user/:name
> 我在user.py中加入以下代码
> def get_name(self, name):
> return self._get('/v2/user/:%s' % name)

之前是否有使用 pip 或 easy_install 过 `douban-client`，感觉像是代码并没有如预期调用你 clone 并修改的那份代码。（太久没用 windows 开发环境，只是猜测）

**Comment by NobodyWHU** [comment]
1.估计第二个问题是由于在申请权限时没有选择豆瓣公共导致的，等明天重新审核通过了，还有问题会继续咨询的。
2.果然是之前用easy_install 安装过，现在修改packages里的代码后问题同上 报错400 。所以一切还等新审核过后再测。  
谢谢您的帮忙啊

**Comment by NobodyWHU** [comment]
1.突然发现 有好多简单的API 代码里面都没实现包装。譬如说电影搜索，在api下的movie.py里并没有看到相应的实现。这些是故意留下来给我们自己定制的吗？
2.with_code方法得到的code 是不是可以一直使用？

**Comment by liluo** [comment]
> 1.突然发现 有好多简单的API 代码里面都没实现包装。譬如说电影搜索，在api下的movie.py里并没有看到相应的实现。这些是故意留下来给我们自己定制的吗？

是根据当时各产品线已有的 API 接口开发的。尔后新增的接口在现基础上也很容易实现，所以就没有持续跟进。

> 2.with_code方法得到的code 是不是可以一直使用？

只可用一次。
