### ISSUE TITLE
怎样知道target应该填什么值？

### ISSUE THREAD

**Issue by ghost** [douban/douban-client#26]
比如在获取某论坛id为'foo'的帖子列表，代码如下：
`client.discussion.list(target, target_id)`
翻遍了文档，我只能确认target_id应该填'foo'，但是我无法从文档中得知target应该赋给什么值。

**Comment by liluo** [comment]
@tianyu0915 

`target` 是指所依附产品对象的名称，如：  https://github.com/douban/douban-client/blob/master/tests/test_api_discussion.py#L11

你需要获取哪里的帖子？

**Comment by ghost** [comment]
@liluo 
非常感谢你的回答。
比如我要获取python小组的讨论列表：http://www.douban.com/group/python/
我不知道对应的target应该填写什么？
换句话说就是，我不知道豆瓣小组“所依附产品对象的名称” 到底是什么。

**Comment by liluo** [comment]
@tianyu0915 

小组 API 并未对外开放（小组是单独的产品，并不属于 `discussion` 的范畴），如有开放计划将会在 [豆瓣 API 小组](http://www.douban.com/group/dbapi/) 和 [开放者平台](http://developers.douban.com/wiki/?title=guide) 公布。

**Comment by ghost** [comment]
好的，问题解决，谢谢。

**Comment by lisongx** [comment]
:cookie:
