### ISSUE TITLE
不能使用一些不需要进行 oAuth 认证就能调用的接口

### ISSUE THREAD

**Issue by bcho** [douban/douban-client#27]
例如这个根据 isbn 获取书籍信息的[接口](http://developers.douban.com/wiki/?title=book_v2#get_isbn_book)，不一定需要通过认证就能进行调用了，但是在 douban-client 里还是需要，否则就会抛出 401 的异常。

粗略看了看实现，所有的接口都继承了 `DoubanApiBase` 这个类，默认调用的时候是检查认证的。那能不能添加另外一个检查选项，让类似 `get_isbn_book` 这样的接口也能直接调用？

**Comment by liluo** [comment]
@bcho 

个人理解, 关于访问公共接口：
- 如果项目本身有用到 OAuth2，在授权时有半截 `access_token` 直接调用即可;
- 如果项目本身并未使用 OAuth2, 使用类似 `urllib` 更轻量更适合一些.

可以具体讲一下你的使用场景吗？  我们一起看下是否需要对 `douban-client` 改进以及怎样的改进.

thx. :smile:

**Comment by bcho** [comment]
@liluo 

hi

是这样的，现在的应用暂时只用到这个 isbn 的查询；不过考虑到以后应该会用到分享、标记之类的功能（就是 _w 的 scope），所以就想先把 `douban_client` 引进来。

不过我还是觉得如果不需要使用 OAuth2 就能调用的接口还是能直接访问就好……

**Comment by liluo** [comment]
@bcho 

理解你的使用场景了。

当初开发时就是以 OAuth2 为前提来设计的，就目前看来需要使用 `douban-client` 来单独访问公共接口的需求并不普遍。

具体到你的项目，前期先使用 Python 标准库 `urllib`, 未来需要分享、标记时再切到 `douban-client` 可以吗?

如果你觉得不是很妥当，我们可以再继续来讨论。

**Comment by bcho** [comment]
@liluo 

唔，我先看看这种组合用起来顺不顺手先，过段时间如果是有问题我再重开这个 issue 吧， thanks :)

**Comment by weakish** [comment]
@bcho  無需認證的訪問也檢查 auth ，我感覺違反直覺。。。

@liluo

> 个人理解, 关于访问公共接口：
> 
> 如果项目本身有用到 OAuth2，在授权时有半截 access_token 直接调用即可;
> 如果项目本身并未使用 OAuth2, 使用类似 urllib 更轻量更适合一些.

如果情況是這樣的：用戶在未綁定豆瓣賬戶的時候仍然可以使用一些基本功能，綁定賬戶後可以使用更多功能。
應該怎麼處理？ 
我現在想到的是，同樣的功能針對綁定和未綁定的情況寫兩套，一套基於requests，另一套基於douban-client（考慮到未 auth 的情況請求頻率限制不同）。
