### ISSUE TITLE
py_oauth2是自己封装的吧？问题太多

### ISSUE THREAD

**Issue by gcd0318** [douban/douban-client#28]
糟糕的结构导致其很难向python3迁移，我想这也是douban-client迟迟不能支持python3的原因，官方不愿搞，民间无法搞

**Comment by gcd0318** [comment]
https://github.com/gcd0318/douban-client
python3移植，修改了py_oauth2，直接解egg然后重新打包，只做了广播配图部分功能，涉及到各种编码方式的转换，没有改版本号。其他部分逐渐跟进

**Comment by liluo** [comment]
@gcd0318 

py-oauth2 在 2 个月前已经有人 PR 支持了 Python 3.x ([具体详情](https://github.com/liluo/py-oauth2/pull/10)) ，我这边测试过可以正常工作(环境 Gentoo + Python 3.2)。如果使用中遇到的问题，可以项目页面[开issue](https://github.com/liluo/py-oauth2/issues/new)，我们可以一块儿来讨论、解决。

关于 douban-client 支持 Python 3.x ，我刚开了个 issue #29，后续会在那里更新进展。

**Comment by gcd0318** [comment]
good job
这个关了吧

**Comment by gcd0318** [comment]
持续保持对python3迁移进度的关注，在完成之前我暂时先用我修改的。因为我对py-oauth2也做对应改动，而且和你前面提供的版本还不太一样，我对文件编码部分做了改变，也因此对douban-client的改动也是对应的。所以这个新的py-oauth2我暂时也还用不上……希望能尽早看到python3的douban-client
