### ISSUE TITLE
ImportError: cannot import name AccessToken

### ISSUE THREAD

**Issue by scudc** [douban/douban-client#3]
```
from oauth2 import Client, AccessToken
```

ImportError: cannot import name AccessToken

我使用给的例子进行测试的时候报出这个错误，去看了下OAuth确实没有这个AccessToken这个模块
不知道怎么处理？？

**Comment by scudc** [comment]
搞定了，安装处了点问题，嘿嘿。

**Comment by liluo** [comment]
好速度。另外说明一下，这里的 oauth2 使用的是 py-oauth2
