### ISSUE TITLE
client.note.get(0) 出现400错误

### ISSUE THREAD

**Issue by riverscn** [douban/douban-client#33]
```
douban_client/api/base.py", line 15, in _check
    raise DoubanAPIError(resp)
douban_client.api.error.DoubanAPIError: ***400 (Bad Request)*** {u'msg': u'target_not_found', u'code': 1006, u'request': u'GET /service/v2/note/0'}
```

**Comment by liluo** [comment]
看一下错误: `{u'msg': u'target_not_found', u'code': 1006, u'request': u'GET /service/v2/note/0'}`

`client.note.get`  需要传入的是日记 ID, ID 为 0 的日记不存在.

**Comment by riverscn** [comment]
id改成1,2,3,4都不行。
用 client.note.list('用户名') 也不行。

```
douban_client/api/base.py", line 15, in _check
    raise DoubanAPIError(resp)
douban_client.api.error.DoubanAPIError: ***400 (Bad Request)*** {u'msg': u'invalid_request_uri', u'code': 107, u'request': u'GET /service/v2/note/user_created/riverscn'}
```

而我的日志肯定是存在的。

**Comment by liluo** [comment]
@riverscn  需要使用的是日记 ID 不是索引值, 如下图:

![screen_shot_2013-12-25_at_11_31_38_am](https://f.cloud.github.com/assets/741755/1807796/696be4fc-6d15-11e3-881c-8de9fc15b7ba.png)

`client.note.list`  传入的需要是豆瓣账号的数字 ID, 拿你的 ID 举例: `client.note.list(1249023)`

如需获取账号数字 ID(及其他信息), 可使用 `client.user.get('riverscn')`, 见结果.

**Comment by riverscn** [comment]
搞定了，理解了~感谢！
