### ISSUE TITLE
通过pip安装报md5不一致错误

### ISSUE THREAD

**Issue by vXaTaVEp** [douban/douban-client#43]
错误描述：

> Collecting douban-client
>   Using cached douban-client-0.0.6.tar.gz
> Collecting py-oauth2>=0.0.8 (from douban-client)
>   Using cached py-oauth2-0.0.10.tar.gz
> Collecting six>=1.4.1 (from douban-client)
>   Using cached six-1.9.0-py2.py3-none-any.whl
> Collecting requests (from py-oauth2>=0.0.8->douban-client)
>   Using cached requests-2.7.0-py2.py3-none-any.whl
>   Hash of the package https://pypi.python.org/packages/2.7/r/requests/requests-2.7.0-py2.py3-none-any.whl#md5=564fb256f865a79f977e57b79d31659a (from https://pypi.python.org/simple/requests/) (9703a9e5b8ddd20165da369ff89a7fbb) doesn't match the expected hash 564fb256f865a79f977e57b79d31659a!
>   Bad md5 hash for package https://pypi.python.org/packages/2.7/r/requests/requests-2.7.0-py2.py3-none-any.whl#md5=564fb256f865a79f977e57b79d31659a (from https://pypi.python.org/simple/requests/)

**Comment by vXaTaVEp** [comment]
－ － 墙的原因

> pip install douban-client -i http://pypi.v2ex.com/simple

**Comment by liluo** [comment]
:ghost:  

有机会也可以尝试一下  `http://pypi.douban.com/simple/`
