### ISSUE TITLE
突然无法授权成功了，是因为频率的原因么，封装以后也看不到错误码

### ISSUE THREAD

**Issue by csufuyi** [douban/douban-client#44]
- [2015/06/04 19:33:46] -     raise ValueError("No JSON object could be decoded") yq34 
  - [2015/06/04 19:33:46] -   File "/usr/local/sae/python/lib/python2.7/json/decoder.py", line 384, in raw_decode yq34 
  - [2015/06/04 19:33:46] -     obj, end = self.raw_decode(s, idx=_w(s, 0).end()) yq34 
  - [2015/06/04 19:33:46] -   File "/usr/local/sae/python/lib/python2.7/json/decoder.py", line 366, in decode yq34 
  - [2015/06/04 19:33:46] -     return _default_decoder.decode(s) yq34 
  - [2015/06/04 19:33:46] -   File "/usr/local/sae/python/lib/python2.7/json/**init**.py", line 338, in loads yq34 
  - [2015/06/04 19:33:46] -     return json.loads(self.text, **kwargs) yq34 
  - [2015/06/04 19:33:46] -   File "/data1/www/htdocs/708/freesz/1/site-packages/requests/models.py", line 741, in json yq34 
  - [2015/06/04 19:33:46] -     return self.resp.json() yq34 
  - [2015/06/04 19:33:46] -   File "/data1/www/htdocs/708/freesz/1/site-packages/pyoauth2/libs/response.py", line 42, in parsed yq34 
  - [2015/06/04 19:33:46] -     opts.update(self.response.parsed) yq34 
  - [2015/06/04 19:33:46] -   File "/data1/www/htdocs/708/freesz/1/site-packages/pyoauth2/client.py", line 39, in get_token yq34

**Comment by liluo** [comment]
你的 api key 通过审核了吗？如果未通过审核，是否使用了非测试用户的账号？

**Comment by liluo** [comment]
另外把调用代码的上下文贴一下？

**Comment by csufuyi** [comment]
# web  douban callback

@app.get('/login')
def greet():
    code = request.GET.get('code', 0)
    guid = request.GET.get('state', None)
    print guid
    client_login.auth_with_code(code)
    uid =  client_login.user.me.get('uid', 0)
    login_kv.set(to_binary(guid), client_login.token_code)
    return template('Hello {{name}}, how are you?', name=uid)

之前一直在使用，这两天用的人多了，就报错了.... client_login.auth_with_code
谢谢啊~

**Comment by csufuyi** [comment]
我的审核通过了的，昨天猛涨了200多用户。

**Comment by csufuyi** [comment]
申请了两个app，都无法使用了。用于微信的是通过审核了的。

# 豆瓣oauth2鉴权

@robot.filter("豆瓣", 'db')
def douban(message, session):
    guid = message.source
    token = get_token(message, session)
    if None != token:
        try:
            client_wechat.auth_with_token(token)
            client_wechat.book.search('哈哈', '', 0, 1)
            return u"豆瓣授权成功! " + u"公众号id:" + guid + u'豆瓣token:'+token
        except:
            print u"豆瓣token失效了"
    # auth again
    auth_des = u'请点我完成豆瓣授权'
    auth_url =  client_wechat.authorize_url + '&state='+ guid
    auth_html = '<a href="%s">%s</a>' % (auth_url,auth_des)
    return auth_html

**Comment by csufuyi** [comment]
过了24点就恢复正常了，应该是有限制。现在用了sdk以后，不方便看错误的细节？只能看到这个？
No JSON object could be decoded

**Comment by pypeng** [comment]
能提供个ip么？可能被封ip了

**Comment by csufuyi** [comment]
ping freesz.sinaapp.com
PING freesz.sinaapp.com (220.181.136.43): 56 data bytes

**Comment by csufuyi** [comment]
sina sae 有人做爬虫，容易被误封ip
